[package]
name = "rclrust-msg-core"
version = "0.0.1"
edition = "2018"
authors = ["Yuma Hiramatsu <yuma.hiramatsu@gmail.com>"]
repository = "https://github.com/ros2rust/ros2rust"
license = "Apache-2.0"

[dev-dependencies]
rand = "0.7"

[build-dependencies]
bindgen = "0.59"
